USE metro_CDMX;


CREATE TABLE `lines` (

   `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

   `name` VARCHAR(15) NOT NULL,
   `color` VARCHAR(20) NOT NULL,
   
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   PRIMARY KEY (`id`)

)
DEFAULT CHARSET=utf8
COLLATE=DEFAULT;


CREATE TABLE `stations` (

   `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

   `name` VARCHAR(50) NOT NULL,

   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,   

   PRIMARY KEY (`id`)

)
DEFAULT CHARSET=utf8
COLLATE=DEFAULT;


CREATE TABLE `trains` (

   `serial_number` VARCHAR(10) NOT NULL,

   `line_id` BIGINT(20) UNSIGNED NOT NULL,
   `type` TINYINT(4) NOT NULL,
   `year` INT(4) NOT NULL,

   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   PRIMARY KEY (`serial_number`),
   
   CONSTRAINT `trains_line_id_foreign`
   FOREIGN KEY (`line_id`) REFERENCES `lines`(`id`)

)
DEFAULT CHARSET=utf8
COLLATE=DEFAULT;


-- Creación de tabla random para un reto de la clase de DELETE
CREATE TABLE `stations_delete` (

   `id` BIGINT(20),

   `name` VARCHAR(50) NOT NULL,
   `icon` VARCHAR(100) NOT NULL,

   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

)
DEFAULT CHARSET=utf8
COLLATE=DEFAULT;